### ISSUE TITLE
cannot use the theme with 2.1.12 because of error

### ISSUE THREAD

**Issue by LarsRabe** [JustCarmen/webtrees-theme-justlight#127]
Theme version 2.2.3 (latest)
```
asort(): Argument #2 ($callback) must be a valid callback, class Fisharebest\Webtrees\I18N does not have a method "strcasecmp" …/modules_v4/jc-theme-justlight/JustlightTheme.php:418
#0 …/modules_v4/jc-theme-justlight/JustlightTheme.php(418): uasort()
#1 …/modules_v4/jc-theme-justlight/JustlightTheme.php(182): JustCarmen\Webtrees\Module\JustlightTheme\JustlightTheme->palettes()
#2 …/app/Http/RequestHandlers/ModuleAction.php(85): JustCarmen\Webtrees\Module\JustlightTheme\JustlightTheme->getAdminAction()
#3 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle()
#4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#5 …/app/Module/CheckForNewVersion.php(115): Middleland\Dispatcher->handle()
#6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#7 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#9 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#10 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#11 …/app/Http/Middleware/Router.php(152): Fisharebest\Webtrees\Webtrees::dispatch()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#13 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#15 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#17 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#19 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle()
#20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#21 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#22 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#23 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#25 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#27 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#29 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#31 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#33 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#35 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#37 …/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle()
#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#39 …/app/Http/Middleware/BadBotBlocker.php(277): Middleland\Dispatcher->handle()
#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#41 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#43 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#45 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#46 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#48 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#50 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle()
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#52 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#54 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#56 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#59 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#60 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#61 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#62 {main}
```

**Comment by LarsRabe** [comment]
After a fresh install with webrees 2.1.13 it works again.
