### ISSUE TITLE
Font color specification

### ISSUE THREAD

**Issue by fisharebest** [JustCarmen/webtrees-theme-justlight#46]
https://github.com/JustCarmen/webtrees-theme-justlight/blob/2.0.7/module.php#L134

The `#` is not needed, and breaks the fan-chart.

See https://www.webtrees.net/index.php/en/forum/help-for-2-0/34926-fan-chart-in-version-2-0-7#80292

**Comment by heiler** [comment]
This was obviously not covered by version 2.0.7.1. I still have the error:

```
Invalid characters passed for attempted conversion, these have been ignored …/app/Module/FanChartModule.php:568
#0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 …/app/Module/FanChartModule.php(568): hexdec()
#2 …/app/Module/FanChartModule.php(298): Fisharebest\Webtrees\Module\FanChartModule->imageColor()
#3 …/app/Module/FanChartModule.php(229): Fisharebest\Webtrees\Module\FanChartModule->chart()
#4 …/app/Http/Middleware/WrapHandler.php(66): Fisharebest\Webtrees\Module\FanChartModule->handle()
#5 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process()
#6 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle()
#7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#8 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle()
#9 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#11 …/app/Http/Middleware/Router.php(134): Middleland\Dispatcher->dispatch()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#13 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle()
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#15 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle()
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#17 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#18 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#19 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#21 …/app/Http/Middleware/DoHousekeeping.php(81): Middleland\Dispatcher->handle()
#22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#23 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle()
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#25 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#27 …/app/Http/Middleware/RegisterFactories.php(73): Middleland\Dispatcher->handle()
#28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterFactories->process()
#29 …/app/Http/Middleware/UseLanguage.php(73): Middleland\Dispatcher->handle()
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#31 …/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher->handle()
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#33 …/app/Http/Middleware/UseFilesystem.php(58): Middleland\Dispatcher->handle()
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process()
#35 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle()
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#37 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle()
#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process()
#39 …/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle()
#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#41 …/app/Http/Middleware/BadBotBlocker.php(213): Middleland\Dispatcher->handle()
#42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#43 …/app/Http/Middleware/UseCache.php(74): Middleland\Dispatcher->handle()
#44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process()
#45 …/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle()
#46 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#48 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#50 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle()
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#52 …/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher->handle()
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#54 …/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle()
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#56 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#58 …/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle()
#59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process()
#60 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#61 …/index.php(57): Middleland\Dispatcher->dispatch()
#62 {main}
```

**Comment by fisharebest** [comment]
@helier - I think you are missing a file.  See #53
